apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: TylerTest1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/cci-sandbox-ananilku6100/run-otel/sample-metrics-app
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
      - image: us-west2-docker.pkg.dev/cci-sandbox-ananilku6100/run-otel/otel-collector-metrics
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133